apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus
  namespace: kic
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: 'true'
config:
  per_consumer: true
  bandwidth_metrics: true
  latency_metrics: true
  status_code_metrics: true
  upstream_health_metrics: true
plugin: prometheus
